name: ci

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    - name: Install dependencies
      run:
        pip install --upgrade pip
        pip install .[lint]
    - name: Lint with black
      run: |
        black --check --diff .
    - name: Lint with isort
      run: |
        isort --check --diff .
    - name: Lint with flake8
      run: |
        flake8

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8,3.9]
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    - name: Run tests with pytest (NumPy)
      run: |
        pip install .[numpy,test]
        BACKEND="Numpy" pytest
    - name: Run tests with pytest (JAX)
      run: |
        pip install .[JAX,test]
        BACKEND="JAX" pytest


  execute-examples:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8,3.9]
        os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    - name: Sync and execute notebooks
      run: |
        pip install .[numpy,jax,example]
        jupytext --sync docs/example_notebooks/*
        python docs/example_notebooks/*.py
