name: ci

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    - name: Install dependencies
      run:
        pip install --upgrade pip
        pip install .[lint]
    - name: Apply linter
      run:
        make lint

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    - name: Install dependencies
      run:
        pip install .[numpy,jax,test]
    - name: Run tests
        make test
        python -m doctest *.md
        python -m doctest odezoo/*.py

  example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    - name: Sync and execute notebooks
      run: |
        pip install .[numpy,jax,example]

  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    - name: Build the HTML docs
      run: |
        pip install .[doc]
        make doc
